services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
        - VITE_GOOGLE_CALENDAR_API_KEY=${VITE_GOOGLE_CALENDAR_API_KEY}
        - VITE_GOOGLE_CALENDAR_CLIENT_ID=${VITE_GOOGLE_CALENDAR_CLIENT_ID}
        - VITE_GOOGLE_CALENDAR_CLIENT_SECRET=${VITE_GOOGLE_CALENDAR_CLIENT_SECRET}
        - VITE_DEBUG_CALENDAR=${VITE_DEBUG_CALENDAR:-false}
        - VITE_APP_NAME=${VITE_APP_NAME:-"Nindra Chatbot System"}
        - VITE_APP_VERSION=${VITE_APP_VERSION:-"1.0.0"}
        - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    # Security settings
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run
      - /var/log/nginx
# Nginx config is copied in Dockerfile, no need for volume mount
