// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzlonndqgowvihbswmav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16bG9ubmRxZ293dmloYnN3bWF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NTQxNjQsImV4cCI6MjA2MjAzMDE2NH0.H5pkb_VBMeIYjjUdhWD_xF16h7CW4ojYCOUTBKeeHvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);